pull_request_rules:
  - name: Approve and merge non-major version dependabot upgrades
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - check-success~=Lint
      - check-success~=Test
      - check-success~=Build Docker
      - title~=^build\(deps[^)]*\). bump [^\s]+ from ([\d]+)\..+ to \1\.
    actions:
      review:
        type: APPROVE
      merge:
        method: squash

  - name: Approve and merge Snyk.io upgrades
    conditions:
      - author=snyk-bot
      - check-success~=Lint
      - check-success~=Test
      - check-success~=Build Docker
      - title~=^\[Snyk\]
    actions:
      review:
        type: APPROVE
      merge:
        method: squash
