FROM node:12-alpine3.9
LABEL maintainer="Open Government Products"
WORKDIR /usr/src/app
RUN apk update && apk add python g++ make tini && rm -rf /var/cache/apk/*
RUN npm install

ENTRYPOINT ["tini", "--"]
CMD ["npm", "run", "dev:start"]
EXPOSE 8080
